"""Constants used throughout the diffusepipe package."""

# Version information
__version__ = "0.1.0"

# Default values
DEFAULT_PIXEL_STEP = 1
DEFAULT_GAIN = 1.0
DEFAULT_MIN_PARTIALITY_THRESHOLD = 0.1

# Status codes
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILURE = "FAILURE"
STATUS_WARNING = "WARNING"

# Pipeline status codes
STATUS_SUCCESS_ALL = "SUCCESS_ALL"
STATUS_SUCCESS_DIALS_ONLY = "SUCCESS_DIALS_ONLY"
STATUS_SUCCESS_EXTRACTION_ONLY = "SUCCESS_EXTRACTION_ONLY"
STATUS_FAILURE_DIALS = "FAILURE_DIALS"
STATUS_FAILURE_EXTRACTION = "FAILURE_EXTRACTION"
STATUS_FAILURE_DIAGNOSTICS = "FAILURE_DIAGNOSTICS"
